services:
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins-pipeline
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      # Volume para o diretório do Jenkins
      - /c/jenkins_home:/var/jenkins_home
      # Volume para o cache do Unity
      - /c/jenkins_home/unity_cache:/root/.cache/unity3d
      # Volume para configurações locais do Unity
      - /c/jenkins_home/unity_local:/root/.local
      # Volume para o Docker socket (necessário para que o Jenkins use Docker dentro do container)
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Variáveis de ambiente (adicione se necessário)
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    user: root # Executa o Jenkins como root para evitar problemas de permissão
    restart: always
