version: "3.8"

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins-container
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS= "-Djenkins.install.runSetupWizard=false"

  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: alves
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - "8082:8080"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8083:80"
    volumes:
      - ./static:/usr/share/nginx/html/static

volumes:
  jenkins_data:
    driver: local
  mysql_data:
    driver: local
