version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts  
    container_name: thirsty_pascal
    ports:
      - "8080:8080"  
      - "50000:50000"  
    volumes:
      - jenkins_data:/var/jenkins_home  
      - /var/run/docker.sock:/var/run/docker.sock  
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: alves
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
  adminer:
    image: adminer
    ports:
      - "8082:8080"

volumes:
  jenkins_data:
    driver: local  
  mysql_data:
    driver: local